### ISSUE TITLE
An incoming call is instantly rejected

### ISSUE THREAD

**Issue by mozhn** [mattkhaw/cordova-plugin-callkit#10]
The problem I mentioned is only on **iOS**. I have a code as below. When the user receives the first notification, the reject callback is triggered immediately. When the second notification is sent immediately after, such a problem does not occur.

```
cordova.plugins.CordovaCall.on('answer', () => {
 this.acceptCall();
});

cordova.plugins.CordovaCall.on('reject', () => {
 this.closeCall();
});
```

closeCall:
```
cordova.plugins.CordovaCall.endCall();
window.twiliovideo.closeRoom();
```

**Comment by mattkhaw** [comment]
I suggest you double check your code and see if you've called the endCall function by mistake. I've recently reimplemented VOIP calls using this version of the plugin and I've never encountered a problem like this. And also, CallKit cannot be tested in iOS simulator. It requires an actual device. The only scenario I could think of with that behaviour is calling the receiveCall function in a simulator.
