### ISSUE TITLE
Can't cancel VoIP notification when application killed [iOS]

### ISSUE THREAD

**Issue by PauMateu** [mattkhaw/cordova-plugin-callkit#11]
We have installed and configured the plugin and, so far, it has worked wonderfully on iOS. So thanks for the work @mattkhaw !!

The only scenario where we are having some trouble with the implementation is the following:

1. **User A** (iOS) has the app killed.
2. **User B** calls **User A**.
3. This plugin handles the VoIP notification and displays the CallUI to **User A**.
4. **User B** hangs up before **User A** accepts the call.
5. A standard push notification is sent to **User A** device to notify that the call has been terminated, but, as **User A** has the application killed, the JS callback that handles the notification behavior and calls `CordovaCall.endCall()` is not executed, and the CallUI notification does not disappear from **User A**s device.

Now, this doesn't happen when the app is in the background or foreground, as the JS callback can be executed without any problem.

How can we handle this situation? Is there any functionality of the plugin that could end the call? Maybe from another ( but different) VoIP? Wouldn't that require to register (yet another) call to iOS?

Any help would be greatly appreciated;
Thanks!

**Comment by mattkhaw** [comment]
As long as CallKit UI is displayed, meaning your app is up and running, which also means that Javascripts can be used. You can verify this by console logging everything. I think to solve this issue, you can try setting a timeout limit on how long the CallKit UI should remain. Once the limit is reached and no notifications received, then you can just end the call and send a notification to notify the caller. By doing it this way, the app should behave according to what you expected.

Another solution is to not use notifications for signaling and use web sockets instead. By doing so, at least the signaling portion is more responsive since it is almost instantaneous. I'm currently using web sockets for this and it works just fine. I have no issues in ending calls.

**Comment by PauMateu** [comment]
Indeed, I didn't realize that the JS was running when the call UI is shown to the user. Thanks for clarifying that!

After some testing, I've realized that, despite the function `CordovaCall.endCall()` being called successfully (the callback onSuccess is executed), the notification UI (the ringing screen) is not hidden and it keeps ringing. Is this the correct way to notify the system that we want the notification to go away? Am I missing something?

Thanks again!

**Comment by mattkhaw** [comment]
From what I know, no. If you use `CordovaCall.receiveCall()` to prompt the UI, definitely use `CordovaCall.endCall()` to terminate it. However, I noticed that the `CordovaCall.endCall()` function is called, there's a slight delay in terminating the UI. Maybe you can add a slight delay before calling `CordovaCall.endCall()`? Maybe that would help?

**Comment by PauMateu** [comment]
As this plugin is launching the UI automatically after receiving a correctly formatted VoIP, I'm not calling `CordovaCall.receiveCall()` directly, I'm letting the  plugin handle the notification and prompt the UI natively. 

Maybe this is why `CordovaCall.endCall()` is not terminating the UI?

**Comment by mattkhaw** [comment]
I'm currently using this plugin, works fine as it is. I can terminate the call screen with no issues.

The plugin instance is declared as a singleton. Like I said, maybe you can add a delay to end the call. See whether that helps or not.

**Comment by PauMateu** [comment]
After some digging, we found out that indeed this plugin works correctly and we were not handling the push notifications to end the call with the function `CordovaCall.endCall()` correctly.

Now it works wonderfully when the app is opened or in foreground. When the app is in the background, however, it seems that, when the user receives a call, despite we can use the JavaScript, and the `onReject`, and `onAnswer` events that cordovaCall provides, some of cordovas functionality does not get executed: it seems as the deviceReady function is not called, and some plugins (like FCMPlugin) are not loaded correctly, thus making it impossible to handle notifications when the phone is blocked.

Is that behavior normal?

**Comment by mattkhaw** [comment]
Just make sure that all of the events that are supposed to be called are hooked properly. As I've mentioned before, 

> As long as CallKit UI is displayed, meaning your app is up and running, which also means that Javascripts can be used.

This will also trigger deviceReady as well. Basically, your app is started normally as if you launch it from the home screen.

**Comment by PauMateu** [comment]
Thanks for the reply!

After a lot of searching, we couldn't figure out why some of the plugins were no loaded correctly when the user opened the app via the callKit UI. We solved it calling `location.reload()` after a call ends and we detect that the plugins were not loaded correctly.
This is far from ideal but it gets the job done for the moment being. Thanks!
