### ISSUE TITLE
Ionic use

### ISSUE THREAD

**Issue by felipedeaguiar** [mattkhaw/cordova-plugin-callkit#14]
First of all congratulations on the work, I would like to know if it is possible to use it on ionic? I'm trying to build a voip using twilio, can this plugin help me?

**Comment by mozhn** [comment]
Yes you can use.

**Comment by felipedeaguiar** [comment]
tks @mozhn ...

how could I make a connection to an incoming call from twilio? can you give an example?

**Comment by mozhn** [comment]
You should send an voip notification to the recipient when an call is made.

**Comment by sys-everton** [comment]
@felipedeaguiar please, have you solved it? I am trying to do the same. Unfortunately no enough informations about how to use it...

**Comment by mattkhaw** [comment]
First of all, this plugin only handles the UI part of the call. The actual call implementation always lies on the SDK that you are using. Please take a look at the SDK documentation.

I'll close this for now since it is not relevant to the plugin.
