### ISSUE TITLE
Does the application run when closed?

### ISSUE THREAD

**Issue by mozhn** [mattkhaw/cordova-plugin-callkit#5]
I have a basic question, does this plugin work when the app is closed? I want to say, does the call screen open when a notification comes while the application is closed?

**Comment by AleksandarTokarev** [comment]
Yes it does, but you have to provide a specific payload. 
See the discussion here.
https://github.com/mattkhaw/cordova-plugin-callkit/issues/4

**Comment by mozhn** [comment]
Thank you
