### ISSUE TITLE
Callkit does not trigger

### ISSUE THREAD

**Issue by mozhn** [mattkhaw/cordova-plugin-callkit#6]
As far as I understand from the error I got in Xcode I'm sending the data wrong. Cannot JSON serialize.

Error:
`[objC] error: -[__NSSingleEntryDictionaryI dataUsingEncoding:]: unrecognized selector sent to instance 0x281c310a0`

Incoming data type
`
NSLog(@"Data type: %@", [data class]);
`
result:
`__NSSingleEntryDictionaryI`

The data I send in my PHP script is as follows:
`
$payload = json_encode(
	array(
		'aps' => array('alert' => 'Test'),
		'data' => array(
		    'Caller' => array('Username' => 'user', 'ConnectionId' => 'user1')
	    )
	)
);
`

**Comment by mattkhaw** [comment]
I've mentioned this before in other closed issues. Just send the payload as a JSON string and not as an object.

**Comment by mozhn** [comment]
Yes sorry, I must have overlooked it. I fixed the problem.
